CREATE TABLE ABTEILUNG (
   ID  INTEGER NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   LEITER INTEGER NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE MITARBEITER (
   ID INTEGER NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   NACHNAME VARCHAR(50) NOT NULL,
   ABTEILUNG INTEGER NOT NULL,
   TELNR VARCHAR(20) NOT NULL,
   MAIL VARCHAR(50) NOT NULL,
   ANSCHRIFT VARCHAR(50) NOT NULL,
   ABTEILUNG_IN_FUEHRUNG INTEGER,
   PRIMARY KEY(ID)

   --VORGESETZTER INTEGER NOT NULL AUTO_INCREMENT,

   --CONSTRAINT FK_MA_VORGESETZTER FOREIGN KEY (VORGESETZTER) REFERENCES MITARBEITER(ID),
);

CREATE TABLE PROJEKT (
   ID INTEGER NOT NULL AUTO_INCREMENT,
   PROJEKT_LEITER INTEGER NOT NULL,
   STUNDENSATZ NUMERIC NOT NULL,
   BUDGET_IN_ARBEITSTAGEN INT NOT NULL,
   AUFTRAGGEBER VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID)

);

CREATE TABLE ZUGANGS_DATEN (
   ID INTEGER NOT NULL,
   USERNAME TEXT NOT NULL ,
   PASSWORD TEXT NOT NULL,
   AUTHORITY VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID)
);

CREATE TABLE TERMIN (
   ID INTEGER NOT NULL AUTO_INCREMENT,
   Titel VARCHAR (150) NOT NULL,
   PROJEKT_ID INTEGER NOT NULL,
   BESCHREIBUNG VARCHAR (150) NOT NULL,
   PRIORITY ENUM('low', 'middle', 'high') NOT NULL,
   VON TIMESTAMP NOT NULL,
   BIS TIMESTAMP NOT NULL,
   PRIMARY KEY(ID)

);

CREATE TABLE PROJEKTVERTEILUNG (
   PROJEKT_ID INTEGER NOT NULL,
   MITARBEITER_ID INTEGER NOT NULL,
   PRIMARY KEY(PROJEKT_ID,MITARBEITER_ID)

);

CREATE TABLE TERMIN_TEILNEHMER (
    TERMIN_ID INTEGER NOT NULL,
    MITARBEITER_ID INTEGER NOT NULL,
    PRIMARY KEY(TERMIN_ID,MITARBEITER_ID)
);

CREATE TABLE KONTINGENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BEZEICHNUNG VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE ZEITERFASSUNG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    MITARBEITER_ID INTEGER NOT NULL,
    KOMMENTAR VARCHAR(50) NOT NULL,
    DAUER NUMERIC NOT NULL,
    DATUM TIMESTAMP NOT NULL,
    PRIMARY KEY(ID)
);

ALTER TABLE ABTEILUNG ADD CONSTRAINT FK_ABTEILUNG_LEITER FOREIGN KEY (LEITER) REFERENCES MITARBEITER(ID);
ALTER TABLE MITARBEITER ADD CONSTRAINT FK_ABTEILUNG_ABTEILUNG_IN_FUEHRUNG FOREIGN KEY (ABTEILUNG_IN_FUEHRUNG) REFERENCES ABTEILUNG(ID);
ALTER TABLE MITARBEITER ADD CONSTRAINT FK_MA_ABTEILUNG FOREIGN KEY (ABTEILUNG) REFERENCES ABTEILUNG(ID);
ALTER TABLE PROJEKT ADD CONSTRAINT FK_PROJECT_LEITER FOREIGN KEY (PROJEKT_LEITER) REFERENCES MITARBEITER(ID);
--ALTER TABLE ZUGANGSDATEN ADD CONSTRAINT ZUGANGSDATEN_PK PRIMARY KEY(USERNAME,PASSWORD);
ALTER TABLE TERMIN_TEILNEHMER ADD CONSTRAINT FK_TERMIN_MA FOREIGN KEY(MITARBEITER_ID) REFERENCES MITARBEITER(ID);
ALTER TABLE TERMIN_TEILNEHMER ADD CONSTRAINT FK_TERMINTEINEHMER_TERMIN FOREIGN KEY(TERMIN_ID) REFERENCES TERMIN(ID);
ALTER TABLE TERMIN ADD CONSTRAINT FK_TERMIN_PROJEKT FOREIGN KEY(PROJEKT_ID) REFERENCES PROJEKT(ID);
--ALTER TABLE PROJEKTVERTEILUNG ADD CONSTRAINT PROJEKTVERTEILUNG_PK PRIMARY KEY(PROJEKT_ID,MITARBEITER_ID);
ALTER TABLE PROJEKTVERTEILUNG ADD CONSTRAINT FK_PROJEKTVERTEILUNG_MA FOREIGN KEY(MITARBEITER_ID) REFERENCES MITARBEITER(ID);
ALTER TABLE PROJEKTVERTEILUNG ADD CONSTRAINT FK_PROJEKTVERTEILUNG_PROJEKT FOREIGN KEY(PROJEKT_ID) REFERENCES PROJEKT(ID);
ALTER TABLE ZEITERFASSUNG ADD CONSTRAINT FK_ZEITERFASSUNG_MA FOREIGN KEY(MITARBEITER_ID) REFERENCES MITARBEITER(ID);

